name: useful_tools
description: event queue...
version: 0.0.4
homepage:
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.17.0
  equatable: ">=2.0.3 <3.0.0"
  flutter:
    sdk: flutter
  meta: any
  nop: ">=0.0.3+1 <1.0.0"
dependency_overrides:
  nop: 
    path: ../nop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any