name: useful_tools
description: event queue...
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  utils:
    path: ../utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0